//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company_Information> Company_Information { get; set; }
        public DbSet<tblUser_Registration> tblUser_Registration { get; set; }
        public DbSet<tblUser_LogInfo> tblUser_LogInfo { get; set; }
        public DbSet<tblEmpAttenApp> tblEmpAttenApps { get; set; }
        public DbSet<tblMenu> tblMenus { get; set; }
        public DbSet<tblBusSchedule> tblBusSchedules { get; set; }
        public DbSet<tblNotice> tblNotices { get; set; }
        public DbSet<tblAlbum> tblAlbums { get; set; }
        public DbSet<tblAlbumGroup> tblAlbumGroups { get; set; }
        public DbSet<tblDeptSec> tblDeptSecs { get; set; }
        public DbSet<tblUserDeptSecPermission> tblUserDeptSecPermissions { get; set; }
        public DbSet<tblEmpOTRequ> tblEmpOTRequs { get; set; }
        public DbSet<tblEmpLeaveApp> tblEmpLeaveApps { get; set; }
        public DbSet<tblOTStatus> tblOTStatus { get; set; }
        public DbSet<tblEmpOTApprovePermission> tblEmpOTApprovePermission { get; set; }
        public DbSet<TblFabricContent> TblFabricContent { get; set; }
        public DbSet<TblFabricColour> TblFabricColour { get; set; }
        public DbSet<TblFabricMill> TblFabricMill { get; set; }
        public DbSet<TblFabricType> TblFabricType { get; set; }
        public DbSet<TblFabricWave> TblFabricWave { get; set; }
        public DbSet<tblFabricInfo> tblFabricInfo { get; set; }
    
        public virtual int prc_EmployeeJobCard(string regId, Nullable<int> month, Nullable<int> year)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EmployeeJobCard", regIdParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeInfoByEmpCode_Result> prc_EmployeeInfoByEmpCode(string compID, string empCode)
        {
            var compIDParameter = compID != null ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(string));
    
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoByEmpCode_Result>("prc_EmployeeInfoByEmpCode", compIDParameter, empCodeParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeInfoByRegId_Result> prc_EmployeeInfoByRegId(string regId)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoByRegId_Result>("prc_EmployeeInfoByRegId", regIdParameter);
        }
    
        public virtual ObjectResult<prc_GetTeamMember_Result> prc_GetTeamMember(string regID)
        {
            var regIDParameter = regID != null ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetTeamMember_Result>("prc_GetTeamMember", regIDParameter);
        }
    
        public virtual int prc_EmployeeLeaveEnjoyDetail(string regId, Nullable<int> year)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EmployeeLeaveEnjoyDetail", regIdParameter, yearParameter);
        }
    
        public virtual int prc_EmployeeLeaveEnjoySummary(string regId, Nullable<int> year)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EmployeeLeaveEnjoySummary", regIdParameter, yearParameter);
        }
    
        public virtual int prc_EmployeeLeaveApplication(Nullable<int> regId, Nullable<System.DateTime> appliedDate, Nullable<int> requestTo, Nullable<int> actingPerson, string lType, Nullable<decimal> lDays, Nullable<System.DateTime> frDate, Nullable<System.DateTime> toDate, string reasons, string status, Nullable<System.DateTime> created_date, string created_By)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(int));
    
            var appliedDateParameter = appliedDate.HasValue ?
                new ObjectParameter("AppliedDate", appliedDate) :
                new ObjectParameter("AppliedDate", typeof(System.DateTime));
    
            var requestToParameter = requestTo.HasValue ?
                new ObjectParameter("RequestTo", requestTo) :
                new ObjectParameter("RequestTo", typeof(int));
    
            var actingPersonParameter = actingPerson.HasValue ?
                new ObjectParameter("ActingPerson", actingPerson) :
                new ObjectParameter("ActingPerson", typeof(int));
    
            var lTypeParameter = lType != null ?
                new ObjectParameter("LType", lType) :
                new ObjectParameter("LType", typeof(string));
    
            var lDaysParameter = lDays.HasValue ?
                new ObjectParameter("LDays", lDays) :
                new ObjectParameter("LDays", typeof(decimal));
    
            var frDateParameter = frDate.HasValue ?
                new ObjectParameter("FrDate", frDate) :
                new ObjectParameter("FrDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var reasonsParameter = reasons != null ?
                new ObjectParameter("Reasons", reasons) :
                new ObjectParameter("Reasons", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("Created_date", created_date) :
                new ObjectParameter("Created_date", typeof(System.DateTime));
    
            var created_ByParameter = created_By != null ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EmployeeLeaveApplication", regIdParameter, appliedDateParameter, requestToParameter, actingPersonParameter, lTypeParameter, lDaysParameter, frDateParameter, toDateParameter, reasonsParameter, statusParameter, created_dateParameter, created_ByParameter);
        }
    
        public virtual int prc_EmployeeLeaveInsertMainDatabase(Nullable<int> regId, Nullable<System.DateTime> appliedDate, Nullable<int> requestTo, Nullable<int> actingPerson, string lType, Nullable<decimal> lDays, Nullable<System.DateTime> frDate, Nullable<System.DateTime> toDate, string reasons, string status, Nullable<System.DateTime> created_date, string created_By)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(int));
    
            var appliedDateParameter = appliedDate.HasValue ?
                new ObjectParameter("AppliedDate", appliedDate) :
                new ObjectParameter("AppliedDate", typeof(System.DateTime));
    
            var requestToParameter = requestTo.HasValue ?
                new ObjectParameter("RequestTo", requestTo) :
                new ObjectParameter("RequestTo", typeof(int));
    
            var actingPersonParameter = actingPerson.HasValue ?
                new ObjectParameter("ActingPerson", actingPerson) :
                new ObjectParameter("ActingPerson", typeof(int));
    
            var lTypeParameter = lType != null ?
                new ObjectParameter("LType", lType) :
                new ObjectParameter("LType", typeof(string));
    
            var lDaysParameter = lDays.HasValue ?
                new ObjectParameter("LDays", lDays) :
                new ObjectParameter("LDays", typeof(decimal));
    
            var frDateParameter = frDate.HasValue ?
                new ObjectParameter("FrDate", frDate) :
                new ObjectParameter("FrDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var reasonsParameter = reasons != null ?
                new ObjectParameter("Reasons", reasons) :
                new ObjectParameter("Reasons", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("Created_date", created_date) :
                new ObjectParameter("Created_date", typeof(System.DateTime));
    
            var created_ByParameter = created_By != null ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_EmployeeLeaveInsertMainDatabase", regIdParameter, appliedDateParameter, requestToParameter, actingPersonParameter, lTypeParameter, lDaysParameter, frDateParameter, toDateParameter, reasonsParameter, statusParameter, created_dateParameter, created_ByParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeAttenApp_Result> prc_EmployeeAttenApp(string regId, Nullable<int> month, Nullable<int> year)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeAttenApp_Result>("prc_EmployeeAttenApp", regIdParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeBirthDay_Result> prc_EmployeeBirthDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeBirthDay_Result>("prc_EmployeeBirthDay");
        }
    
        public virtual ObjectResult<prc_UserMenu_Result> prc_UserMenu(string regId)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_UserMenu_Result>("prc_UserMenu", regIdParameter);
        }
    
        public virtual ObjectResult<prc_CopyBusSchedule_Result> prc_CopyBusSchedule(string iDs, Nullable<System.DateTime> toDate, string created_By)
        {
            var iDsParameter = iDs != null ?
                new ObjectParameter("IDs", iDs) :
                new ObjectParameter("IDs", typeof(string));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var created_ByParameter = created_By != null ?
                new ObjectParameter("Created_By", created_By) :
                new ObjectParameter("Created_By", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_CopyBusSchedule_Result>("prc_CopyBusSchedule", iDsParameter, toDateParameter, created_ByParameter);
        }
    
        public virtual ObjectResult<prc_GetAlbum_Result> prc_GetAlbum(Nullable<int> group, Nullable<System.DateTime> afterDate, string name)
        {
            var groupParameter = group.HasValue ?
                new ObjectParameter("Group", group) :
                new ObjectParameter("Group", typeof(int));
    
            var afterDateParameter = afterDate.HasValue ?
                new ObjectParameter("AfterDate", afterDate) :
                new ObjectParameter("AfterDate", typeof(System.DateTime));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetAlbum_Result>("prc_GetAlbum", groupParameter, afterDateParameter, nameParameter);
        }
    
        public virtual ObjectResult<prc_GetAlbumByGroupID_Result> prc_GetAlbumByGroupID(Nullable<int> group)
        {
            var groupParameter = group.HasValue ?
                new ObjectParameter("Group", group) :
                new ObjectParameter("Group", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetAlbumByGroupID_Result>("prc_GetAlbumByGroupID", groupParameter);
        }
    
        public virtual ObjectResult<Prc_OTRequ_Reset_Result> Prc_OTRequ_Reset(Nullable<int> compID, Nullable<System.DateTime> date, string department, string section)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_OTRequ_Reset_Result>("Prc_OTRequ_Reset", compIDParameter, dateParameter, departmentParameter, sectionParameter);
        }
    
        public virtual ObjectResult<Prc_OTRequ_Approve_Result> Prc_OTRequ_Approve(Nullable<int> compID, Nullable<System.DateTime> date, string department, string section, string oTRequ, string wstatus, Nullable<bool> approved, Nullable<bool> isLock, string updated_by)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            var oTRequParameter = oTRequ != null ?
                new ObjectParameter("OTRequ", oTRequ) :
                new ObjectParameter("OTRequ", typeof(string));
    
            var wstatusParameter = wstatus != null ?
                new ObjectParameter("Wstatus", wstatus) :
                new ObjectParameter("Wstatus", typeof(string));
    
            var approvedParameter = approved.HasValue ?
                new ObjectParameter("Approved", approved) :
                new ObjectParameter("Approved", typeof(bool));
    
            var isLockParameter = isLock.HasValue ?
                new ObjectParameter("IsLock", isLock) :
                new ObjectParameter("IsLock", typeof(bool));
    
            var updated_byParameter = updated_by != null ?
                new ObjectParameter("Updated_by", updated_by) :
                new ObjectParameter("Updated_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_OTRequ_Approve_Result>("Prc_OTRequ_Approve", compIDParameter, dateParameter, departmentParameter, sectionParameter, oTRequParameter, wstatusParameter, approvedParameter, isLockParameter, updated_byParameter);
        }
    
        public virtual ObjectResult<prc_GetEmpDeptSec_Result> prc_GetEmpDeptSec(Nullable<int> regID, string type)
        {
            var regIDParameter = regID.HasValue ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_GetEmpDeptSec_Result>("prc_GetEmpDeptSec", regIDParameter, typeParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeInfoDetail_Result> prc_EmployeeInfoDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfoDetail_Result>("prc_EmployeeInfoDetail");
        }
    
        public virtual ObjectResult<prc_EmployeeInfo_Result> prc_EmployeeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeInfo_Result>("prc_EmployeeInfo");
        }
    
        public virtual ObjectResult<Prc_Get_OTRequ_Summary_Result> Prc_Get_OTRequ_Summary(Nullable<int> compID, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_Get_OTRequ_Summary_Result>("Prc_Get_OTRequ_Summary", compIDParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeLeaveStatus_Result> prc_EmployeeLeaveStatus(string regId, Nullable<int> year)
        {
            var regIdParameter = regId != null ?
                new ObjectParameter("RegId", regId) :
                new ObjectParameter("RegId", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeLeaveStatus_Result>("prc_EmployeeLeaveStatus", regIdParameter, yearParameter);
        }
    
        public virtual ObjectResult<prc_Get_OTRequEmail_Result> prc_Get_OTRequEmail(Nullable<int> compID, Nullable<System.DateTime> dateFrom)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_Get_OTRequEmail_Result>("prc_Get_OTRequEmail", compIDParameter, dateFromParameter);
        }
    
        public virtual int Prc_Get_OTApprove_Summary_Info(Nullable<int> comPID, Nullable<System.DateTime> date, string department, string section, Nullable<int> sIGN)
        {
            var comPIDParameter = comPID.HasValue ?
                new ObjectParameter("ComPID", comPID) :
                new ObjectParameter("ComPID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            var sIGNParameter = sIGN.HasValue ?
                new ObjectParameter("SIGN", sIGN) :
                new ObjectParameter("SIGN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Prc_Get_OTApprove_Summary_Info", comPIDParameter, dateParameter, departmentParameter, sectionParameter, sIGNParameter);
        }
    
        public virtual int Prc_Get_OTApprove_Summary(Nullable<int> comPID, Nullable<System.DateTime> date, string department, string section, Nullable<int> sIGN)
        {
            var comPIDParameter = comPID.HasValue ?
                new ObjectParameter("ComPID", comPID) :
                new ObjectParameter("ComPID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            var sIGNParameter = sIGN.HasValue ?
                new ObjectParameter("SIGN", sIGN) :
                new ObjectParameter("SIGN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Prc_Get_OTApprove_Summary", comPIDParameter, dateParameter, departmentParameter, sectionParameter, sIGNParameter);
        }
    
        public virtual ObjectResult<Prc_Get_OTRequ_Info_Result> Prc_Get_OTRequ_Info(Nullable<int> compID, Nullable<System.DateTime> date, string department, string section)
        {
            var compIDParameter = compID.HasValue ?
                new ObjectParameter("CompID", compID) :
                new ObjectParameter("CompID", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var sectionParameter = section != null ?
                new ObjectParameter("Section", section) :
                new ObjectParameter("Section", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_Get_OTRequ_Info_Result>("Prc_Get_OTRequ_Info", compIDParameter, dateParameter, departmentParameter, sectionParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeAttenInfo_Result> prc_EmployeeAttenInfo(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeAttenInfo_Result>("prc_EmployeeAttenInfo", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<prc_EmployeeLeaveInfo_Result> prc_EmployeeLeaveInfo(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_EmployeeLeaveInfo_Result>("prc_EmployeeLeaveInfo", monthParameter, yearParameter);
        }
    }
}
