//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlbum
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SnapDate { get; set; }
        public string URL { get; set; }
        public string TemplateImage { get; set; }
        public bool YSNActive { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
