//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusSchedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string RoadName { get; set; }
        public string RoadDescription { get; set; }
        public string StartingPoint { get; set; }
        public string Destination { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string Driver { get; set; }
        public Nullable<int> PassengerCapacity { get; set; }
        public string Wstatus { get; set; }
        public Nullable<bool> Publish { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
