//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpOTApprovePermission
    {
        public Nullable<int> ID { get; set; }
        public int RegId { get; set; }
        public int ComID { get; set; }
        public string EmpInfo { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> PublishActive { get; set; }
        public Nullable<bool> YsnActive { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
