//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpOTRequ
    {
        public long ComID { get; set; }
        public System.DateTime Date { get; set; }
        public string EmpCode { get; set; }
        public string RequestOT { get; set; }
        public string OTRequ { get; set; }
        public string Reasons { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public string EditReason { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
