//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpAttenApp
    {
        public int RegId { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public System.DateTime prDate { get; set; }
        public string TimeIn { get; set; }
        public string LateHrs { get; set; }
        public string TimeOut { get; set; }
        public string DailyHrs { get; set; }
        public string ValidOT { get; set; }
        public string RestOT { get; set; }
        public string ExtraOT { get; set; }
        public string Status { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> TransAllow { get; set; }
        public string Reasons { get; set; }
        public Nullable<bool> Process { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
