//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpLeaveApp
    {
        public int RegId { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public int RequestTo { get; set; }
        public int ActingPerson { get; set; }
        public string LType { get; set; }
        public decimal LDays { get; set; }
        public System.DateTime FrDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Reasons { get; set; }
        public string Status { get; set; }
        public string StatusReasons { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
