//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacificPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFabricInfo
    {
        public int Slno { get; set; }
        public string FabricCode { get; set; }
        public string PJLCode { get; set; }
        public int MillID { get; set; }
        public int ContentID { get; set; }
        public double Weight { get; set; }
        public string WeightUnit { get; set; }
        public string WeightType { get; set; }
        public string FabricConst { get; set; }
        public string Width { get; set; }
        public string WidthUnit { get; set; }
        public int ColourID { get; set; }
        public int FabricTypeID { get; set; }
        public int WeaveID { get; set; }
        public string FabricFinish { get; set; }
        public double Price { get; set; }
        public string PriceUnit { get; set; }
        public string PriceType { get; set; }
        public string Remarks { get; set; }
        public string CNFPrice { get; set; }
        public string Fabricwarp { get; set; }
        public string Fabricwaft { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string Updated_by { get; set; }
    }
}
